project_id = "mlldxagtunmtcrtlwgfd"

[functions.address-autocomplete]
verify_jwt = false

[functions.detect-country]
verify_jwt = false

[functions.send-telegram]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-settings]
verify_jwt = false

[functions.admin-sessions]
verify_jwt = false